# Generated by Django 6.1 on 2026-09-01 20:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('account_age_days', models.IntegerField(help_text='How old the account is, in days')),
                ('total_orders', models.IntegerField(default=0)),
                ('total_returns', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(help_text='Amount in paise')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('category', models.CharField(help_text='e.g. electronics, apparel, grocery', max_length=50)),
                ('delivery_status', models.CharField(choices=[('delivered', 'Delivered'), ('in_transit', 'In Transit'), ('failed', 'Failed')], default='delivered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='risk.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_refund_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.CharField(choices=[('damaged', 'Damaged Item'), ('wrong_item', 'Wrong Item Sent'), ('size_issue', 'Size/Fit Issue'), ('changed_mind', 'Changed Mind'), ('not_as_described', 'Not As Described'), ('other', 'Other')], max_length=50)),
                ('days_to_return', models.IntegerField(help_text='Days between delivery and return request')),
                ('refund_amount', models.IntegerField(help_text='Amount refunded, in paise')),
                ('is_actually_risky', models.BooleanField(default=False, help_text='Ground truth label used only for precision/recall eval')),
                ('split', models.CharField(choices=[('train', 'Train'), ('test', 'Held-out Test')], default='train', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='risk.order')),
            ],
        ),
        migrations.CreateModel(
            name='RiskVerdict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_score', models.FloatField(help_text='0.0 (safe) to 1.0 (high risk)')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('predicted_risky', models.BooleanField(default=False, help_text='True if risk_score crosses your chosen threshold (e.g. >= 0.6)')),
                ('reasoning', models.TextField(help_text="Claude's natural-language explanation")),
                ('estimated_fp_cost', models.IntegerField(default=0, help_text='Estimated cost in paise if this flag turns out to be a false positive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('return_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_verdict', to='risk.returnrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approve', 'Approve Refund'), ('flag_for_review', 'Flag for Human Review'), ('deny', 'Deny Refund')], max_length=20)),
                ('reasoning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk_verdict', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_decision', to='risk.riskverdict')),
            ],
        ),
    ]
